extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_f3dlite_material_lights;
extern Lights1 bob_dl_f3dlite_material_001_lights;
extern Lights1 bob_dl_f3dlite_material_002_lights;
extern Lights1 bob_dl_f3dlite_material_003_lights;
extern Lights1 bob_dl_f3dlite_material_004_lights;
extern Lights1 bob_dl_f3dlite_material_005_lights;
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[96];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_0[98];
extern Gfx bob_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_0[153];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_003_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_003_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_004_mesh_layer_1_vtx_0[162];
extern Gfx bob_dl_Cube_004_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_005_mesh_layer_1_vtx_0[68];
extern Gfx bob_dl_Cube_005_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_f3dlite_material[];
extern Gfx mat_bob_dl_f3dlite_material_001[];
extern Gfx mat_bob_dl_f3dlite_material_002[];
extern Gfx mat_bob_dl_f3dlite_material_003[];
extern Gfx mat_bob_dl_f3dlite_material_004[];
extern Gfx mat_bob_dl_f3dlite_material_005[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Cube_001_mesh_layer_1[];
extern Gfx bob_dl_Cube_002_mesh_layer_1[];
extern Gfx bob_dl_Cube_003_mesh_layer_1[];
extern Gfx bob_dl_Cube_004_mesh_layer_1[];
extern Gfx bob_dl_Cube_005_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
